name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup virtualenv
        run: |
          python -V
          python -m pip install virtualenv pipdeptree
          virtualenv venv
          source venv/bin/activate
          pip install --upgrade pip

      - name: Check pre-commit status
        run: |
          pip install .[tests,databricks]
          pip freeze
          pipdeptree
          pre-commit run --all-files

      - name: Test with tox
        run: |
          tox

      - name: Report coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE }}
        with:
          coverageCommand: coverage xml
          debug: true
          coverageLocations: coverage.xml:coverage.py
